from setuptools import setup, find_packages

setup(
    name="leanworks",
    version="0.6.1",
    packages=find_packages(),
    install_requires=[
        "kubernetes==31.0.0",
        "google-cloud-storage==2.14.0",
        "google-cloud-bigquery==3.0.0",
        "google-cloud-vectorsearch==0.3.0",
        "google-cloud-secret-manager==2.22.0",
        "google-auth==2.37.0",
        "google-auth-oauthlib==1.2.1",
        "google-auth-httplib2==0.2.0",
        "anthropic==0.75.0",
        "google-genai==1.24.0",
        "google-cloud-aiplatform==1.60.0",
        "openai==1.60.0",
        "google-api-python-client==2.159.0",
        "numpy==1.26.0",
        "tiktoken==0.9.0",
        "pyyaml==6.0.2",
        "firebase-admin==6.4.0",
        "requests==2.32.4",
        "msal==1.33.0",
        "python-dotenv==1.0.1",
        "pytz==2024.1",
        "duckdb==1.1.3",
        "psycopg2-binary==2.9.11",
        "nltk==3.8.1",
        "PyJWT==2.8.0",
        "cryptography==41.0.0",
        "httpx==0.28.1",
        "markdown==3.5.2",
    ],
    author="Yanfu Zhu",
    author_email="yanfu@leanworks.ai",
    description="Internal LeanWorks package",
    python_requires=">=3.10",
    url="https://github.com/LeanWorks-ai/leanworks",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
) 
